name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
     - main
     - jenk
  workflow_dispatch:
jobs:
 Myjobs:
  runs-on: ubuntu-latest
        
  steps:
        - name: Set up JDK 17 
          uses: actions/setup-java@v3
          with:
              java-version: '17'
              distribution: 'zulu'
              
        - name: Show Java version
           run:"java -version" 
               
        - name: Check out repository code
          uses: actions/checkout@v3   
          with:
           ref: jenk

        - name: Show current directory
           run:'pwd'
             
        - name: Show all files
           run:'ls-la'

        - name: Install Dependencies
            run:'mvn compile'
             
        - name: Build App
            run:'mvn package -DskipTest'
             
        - name: Test app
            run:'mvn test'
